create extension if not exists pgcrypto;

create type public.user_role as enum ('user', 'admin');
create type public.sticker_status as enum ('owned', 'missing', 'duplicate');
create type public.trade_status as enum ('available', 'reserved', 'traded');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null default 'Sammler',
  avatar_url text,
  role public.user_role not null default 'user',
  created_at timestamptz not null default now()
);

create table public.countries (
  id bigint generated by default as identity primary key,
  code text not null unique check (char_length(code) between 3 and 4),
  name text not null,
  created_at timestamptz not null default now()
);

create table public.stickers (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  sticker_number integer not null check (sticker_number > 0),
  created_at timestamptz not null default now(),
  unique (country_id, sticker_number)
);

create table public.user_stickers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  sticker_id bigint not null references public.stickers(id) on delete cascade,
  status public.sticker_status not null default 'missing',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, sticker_id)
);

create table public.trades (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references public.profiles(id) on delete cascade,
  sticker_id bigint not null references public.stickers(id) on delete cascade,
  status public.trade_status not null default 'available',
  created_at timestamptz not null default now(),
  unique (owner_user_id, sticker_id)
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.import_stickers(rows jsonb)
returns integer language plpgsql security definer set search_path = public
as $$
declare
  item jsonb;
  country_id_value bigint;
  imported integer := 0;
begin
  if not public.is_admin() then
    raise exception 'Nur Administratoren dürfen Sticker importieren.';
  end if;

  for item in select * from jsonb_array_elements(rows)
  loop
    insert into public.countries (code, name)
    values (upper(item ->> 'country_code'), upper(item ->> 'country_code'))
    on conflict (code) do update set code = excluded.code
    returning id into country_id_value;

    insert into public.stickers (country_id, sticker_number)
    values (country_id_value, (item ->> 'sticker_number')::integer)
    on conflict (country_id, sticker_number) do nothing;
    imported := imported + 1;
  end loop;
  return imported;
end;
$$;

create or replace view public.user_statistics
with (security_invoker = true)
as
select
  p.id,
  p.display_name,
  count(us.*) filter (where us.status = 'owned') as owned,
  count(us.*) filter (where us.status = 'duplicate') as duplicates,
  count(s.*) - count(us.*) filter (where us.status in ('owned', 'duplicate')) as missing,
  round(
    100.0 * count(us.*) filter (where us.status in ('owned', 'duplicate'))
    / nullif(count(s.*), 0)
  ) as completion
from public.profiles p
cross join public.stickers s
left join public.user_stickers us on us.user_id = p.id and us.sticker_id = s.id
group by p.id, p.display_name;

create or replace function public.get_user_statistics()
returns table (
  id uuid,
  display_name text,
  owned bigint,
  duplicates bigint,
  missing bigint,
  completion numeric
)
language sql stable security definer set search_path = public
as $$
  select
    p.id,
    p.display_name,
    count(us.*) filter (where us.status = 'owned') as owned,
    count(us.*) filter (where us.status = 'duplicate') as duplicates,
    count(s.*) - count(us.*) filter (where us.status in ('owned', 'duplicate')) as missing,
    round(
      100.0 * count(us.*) filter (where us.status in ('owned', 'duplicate'))
      / nullif(count(s.*), 0)
    ) as completion
  from public.profiles p
  cross join public.stickers s
  left join public.user_stickers us on us.user_id = p.id and us.sticker_id = s.id
  group by p.id, p.display_name
  order by completion desc nulls last
  limit 10;
$$;

alter table public.profiles enable row level security;
alter table public.countries enable row level security;
alter table public.stickers enable row level security;
alter table public.user_stickers enable row level security;
alter table public.trades enable row level security;

create policy "Profiles visible to authenticated users"
  on public.profiles for select to authenticated using (true);
create policy "Users update own profile"
  on public.profiles for update to authenticated using (id = auth.uid());
create policy "Admins manage profiles"
  on public.profiles for all to authenticated using (public.is_admin());

create policy "Countries are readable"
  on public.countries for select to authenticated using (true);
create policy "Admins manage countries"
  on public.countries for all to authenticated using (public.is_admin());

create policy "Stickers are readable"
  on public.stickers for select to authenticated using (true);
create policy "Admins manage stickers"
  on public.stickers for all to authenticated using (public.is_admin());

create policy "Users read own stickers"
  on public.user_stickers for select to authenticated using (user_id = auth.uid());
create policy "Users insert own stickers"
  on public.user_stickers for insert to authenticated with check (user_id = auth.uid());
create policy "Users update own stickers"
  on public.user_stickers for update to authenticated using (user_id = auth.uid());
create policy "Users delete own stickers"
  on public.user_stickers for delete to authenticated using (user_id = auth.uid());

create policy "Trades are readable"
  on public.trades for select to authenticated using (true);
create policy "Users publish own trades"
  on public.trades for insert to authenticated with check (owner_user_id = auth.uid());
create policy "Users update own trades"
  on public.trades for update to authenticated using (owner_user_id = auth.uid());
create policy "Users delete own trades"
  on public.trades for delete to authenticated using (owner_user_id = auth.uid());

grant select on public.user_statistics to authenticated;
grant execute on function public.import_stickers(jsonb) to authenticated;
grant execute on function public.get_user_statistics() to authenticated;
